include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    type_annotate_public_apis: error
    exhaustive_cases: error
    unawaited_futures: error
    discarded_futures: error
    avoid_dynamic_calls: error

linter:
  rules:
    # API hygiene
    - type_annotate_public_apis
    - always_declare_return_types
    - public_member_api_docs
    - library_private_types_in_public_api

    # Safety & correctness
    - exhaustive_cases
    - unawaited_futures
    - discarded_futures
    - avoid_dynamic_calls
    - avoid_annotating_with_dynamic
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - do_not_use_environment
    - avoid_returning_null_for_future
    - avoid_void_async

    # Immutability & predictability
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_final_parameters
    - prefer_const_constructors
    - prefer_const_declarations

    # Imports & structure
    - prefer_relative_imports
    - combinators_ordering
    - directives_ordering
    - sort_pub_dependencies
    - require_trailing_commas
    - file_names
    - package_names

    # Perf / cleanup
    - avoid_print
    - avoid_redundant_argument_values
    - collection_methods_unrelated_type

    # Flutter
    - prefer_const_literals_to_create_immutables
